server:
  extraArgs:
    - "--insecure"
  service:
    type: LoadBalancer
    # annotations:
    #   metallb.universe.tf/address-pool: default 
    loadBalancerIP: 192.168.1.102

redis:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi

controller:
  replicas: 1
  persistence:
    enabled: true
    size: 1Gi
repoServer:
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  persistence:
    enabled: true
    size: 1Gi
dex:
  enabled: false
