kubeProxyReplacement: true
k8sServiceHost: "192.168.1.100"
k8sServicePort: 6443

operator:
  replicas: 1
  prometheus:
    enabled: true

l2announcements:
  enabled: true

bgpControlPlane:
  enabled: true

k8sClientRateLimit:
  qps: 80
  burst: 150

externalIPs:
  enabled: true

pmtuDiscovery:
  enabled: true

# enableIPv4Masquerade: false
bpf:
  hostLegacyRouting: true
  masquerade: true
localRedirectPolicy: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true

hubble:
  enabled: true
  prometheus:
    enabled: true
  metrics:
    enabled:
      - dns
      - http
      - tcp
      - flow
  relay:
    enabled: true
  ui:
    enabled: true
    rollOutPods: true
