logLevel: warn
expose:
  type: loadBalancer
  tls:
    enabled: true
    auto:
      commonName: "harbor.server.local"

  loadBalancer:
    name: harbor
    IP: "192.168.1.105"
    ports:
      httpPort: 80
      httpsPort: 443

externalURL: "https://harbor.server.local"
harborAdminPassword: "nAynDDii9B"
registry:
  relativeurls: true
