logLevel: warn
expose:
  type: loadBalancer
#  tls:
#    enabled: false
  loadBalancer:
    name: harbor
    IP: "192.168.1.105"
    ports:
      httpPort: 80
      httpsPort: 443
externalURL: "http://harbor.server.local"
harborAdminPassword: "nAynDDii9B"