server:
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: longhorn
  service:
    type: ClusterIP
    # port: 80
    # targetPort: 80
  ha:
    enabled: false
    replicas: 1
ui:
  enabled: true
  serviceType: LoadBalancer
  # externalPort: 80
  # targetPort: 80
  loadBalancerIP: 192.168.1.101
